name: Develop Branch Build and Deploy Front-end
on:
  push: # Currently, every time it is pushed to this branch, it will execute the job
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Create .env file
        run: |
          touch .env | echo "${{ secrets.ENVIRONMENT_TESTNET }}" > .env
      - name: Build
        run: CI=false npm run build # CI=false should be removed for prod
      - name: Archive build artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Create firebase.json
        run: |
          echo '${{ secrets.FIREBASE_TESTNET_CONFIG }}' > firebase.json
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_TESTNET }}
